#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    layout                       bsp            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on             \
                                                \
    top_padding                  0              \
    bottom_padding               0              \
    left_padding                 0              \
    right_padding                0              \
    window_gap                   0              \
                                                \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
                                                \
    window_topmost               off            \
    window_opacity               off            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_shadow                float          \
                                                \
    window_border                off            \
    window_border_width          2              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    insert_feedback_color        0xffd75f5f     \
                                                \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
                                                \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^System Settings$" manage=off sticky=on
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^Messages$" manage=off sticky=on
yabai -m rule --add app="^Digital Color Meter$" manage=off sticky=on layer=above
yabai -m rule --add app="^IINA$" manage=off

SPACEBAR_HEIGHT=$(sketchybar --query bar | jq .height)
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

echo "yabai configuration loaded.."
